spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:MOYEOU_DB
    username: user
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

jwt:
  secret-key: "secret-test"
  refresh-key: "refresh-test"
