### 회원 가입(host)
POST http://localhost:8080/sign-up
Content-Type: application/json

{
  "email": "host@email.com",
  "password": "password",
  "nickname": "host",
  "department": "컴퓨터공학과",
  "studentNumber": "202300001"
}

### 로그인(host)
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "host@email.com",
  "password": "password"
}


### 회원 가입(member1)
POST http://localhost:8080/sign-up
Content-Type: application/json

{
  "email": "member1@email.com",
  "password": "password",
  "nickname": "member1",
  "department": "기계공학과",
  "studentNumber": "202300002"
}


### 로그인(member1)
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "member1@email.com",
  "password": "password"
}


### 회원 가입(member2)
POST http://localhost:8080/sign-up
Content-Type: application/json

{
  "email": "member2@email.com",
  "password": "password",
  "nickname": "member2",
  "department": "기계공학과",
  "studentNumber": "202300003"
}


### 로그인(member2)
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "member2@email.com",
  "password": "password"
}


### sse 연결(host)
GET http://localhost:8080/subscribe
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkzODIxMjg5LCJleHAiOjE2OTM4MjQ4ODl9.cjp4Ww2n360CNm2OhE-gswMqQezE9grZWDbjgNiuwbE


### sse 연결(member1)
GET http://localhost:8080/subscribe
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjkzODIxMzY5LCJleHAiOjE2OTM4MjQ5Njl9.vbNy7LhNd0lE6MZuzccQt3NAgIWg7GQLDnqea8xYuDc


### sse 연결(member2)
GET http://localhost:8080/subscribe
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjkzODIxNDA4LCJleHAiOjE2OTM4MjUwMDh9.ouosB4OBgltHMaKrqYcTihYyKt8QkBrz_xPN2UJ_LNs


### 게시물 생성
POST http://localhost:8080/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkzODIxMjg5LCJleHAiOjE2OTM4MjQ4ODl9.cjp4Ww2n360CNm2OhE-gswMqQezE9grZWDbjgNiuwbE

{
  "operationWay": "온라인",
  "headCount": 3,
  "expectedDate": "2023-06-01",
  "title": "스터디 모집합니다",
  "estimatedDuration": "3개월",
  "content": "꾸준히 하실 분",
  "items": [
    "Github",
    "흥미있는 분야"
  ]
}


### 게시물 조회
GET http://localhost:8080/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkzODIxMjg5LCJleHAiOjE2OTM4MjQ4ODl9.cjp4Ww2n360CNm2OhE-gswMqQezE9grZWDbjgNiuwbE


### 게시물 신청 폼 조회
GET http://localhost:8080/posts/1/form
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjkzODIxMzY5LCJleHAiOjE2OTM4MjQ5Njl9.vbNy7LhNd0lE6MZuzccQt3NAgIWg7GQLDnqea8xYuDc


### 댓글 작성(member1)
POST http://localhost:8080/posts/1/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjkzODIxMzY5LCJleHAiOjE2OTM4MjQ5Njl9.vbNy7LhNd0lE6MZuzccQt3NAgIWg7GQLDnqea8xYuDc

{
  "content": "~~~~~~~~?"
}


### 모집 신청(member1)
POST http://localhost:8080/posts/1/attend
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjkzODIxMzY5LCJleHAiOjE2OTM4MjQ5Njl9.vbNy7LhNd0lE6MZuzccQt3NAgIWg7GQLDnqea8xYuDc

{
  "answers": [
    {
      "itemId": 1,
      "answer": "abcd"
    },
    {
      "itemId": 2,
      "answer": "백엔드"
    }
  ]
}


### 모집 신청(member2)
POST http://localhost:8080/posts/1/attend
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjkzODIxNDA4LCJleHAiOjE2OTM4MjUwMDh9.ouosB4OBgltHMaKrqYcTihYyKt8QkBrz_xPN2UJ_LNs

{
  "answers": [
    {
      "itemId": 1,
      "answer": "ㅎㅎㅎㅎㅎ"
    },
    {
      "itemId": 2,
      "answer": "ㅋㅋㅋㅋㅋ"
    }
  ]
}


### 알림 확인(host)
GET http://localhost:8080/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkzODIxMjg5LCJleHAiOjE2OTM4MjQ4ODl9.cjp4Ww2n360CNm2OhE-gswMqQezE9grZWDbjgNiuwbE


### 신청 수락(host -> member1)
POST http://localhost:8080/posts/1/participations/2/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkzODIxMjg5LCJleHAiOjE2OTM4MjQ4ODl9.cjp4Ww2n360CNm2OhE-gswMqQezE9grZWDbjgNiuwbE


### 신청 거절(host -> member2)
POST http://localhost:8080/posts/1/participations/3/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkzODIxMjg5LCJleHAiOjE2OTM4MjQ4ODl9.cjp4Ww2n360CNm2OhE-gswMqQezE9grZWDbjgNiuwbE


### 알림 확인(member2)
GET http://localhost:8080/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzIiwiaWF0IjoxNjkzODIxNDA4LCJleHAiOjE2OTM4MjUwMDh9.ouosB4OBgltHMaKrqYcTihYyKt8QkBrz_xPN2UJ_LNs


### 모집 완료(host)
POST http://localhost:8080/posts/1/complete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjkzODIxMjg5LCJleHAiOjE2OTM4MjQ4ODl9.cjp4Ww2n360CNm2OhE-gswMqQezE9grZWDbjgNiuwbE


### 알림 확인(member1)
GET http://localhost:8080/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjkzODIxMzY5LCJleHAiOjE2OTM4MjQ5Njl9.vbNy7LhNd0lE6MZuzccQt3NAgIWg7GQLDnqea8xYuDc
