### 게시물 생성
POST http://52.79.241.162:8080/posts
Content-Type: application/json
Authorization: Bearer

{
  "operationWay": "온라인",
  "headCount": 3,
  "expectedDate": "2023-06-01",
  "title": "스터디 모집합니다",
  "estimatedDuration": "3개월",
  "content": "꾸준히 하실 분",
  "items": [
    "Github",
    "흥미있는 분야"
  ],
  "hashtags": [
    "공과대학",
    "코딩테스트"
  ]
}

### 게시물 생성
POST http://52.79.241.162:8080/posts
Content-Type: application/json
Authorization: Bearer

{
  "operationWay": "대면",
  "headCount": 5,
  "expectedDate": "2023-11-01",
  "title": "모집합니다 모집합니다",
  "estimatedDuration": "5개월",
  "content": "코딩테스트 준비해요",
  "items": [
    "Github",
    "사용 언어"
  ],
  "hashtags": [
    "공과대학",
    "코딩테스트",
    "백엔드"
  ]
}

### 게시물 조회
GET http://52.79.241.162:8080/posts/4
Authorization: Bearer


### 게시물 삭제
DELETE http://52.79.241.162:8080/posts/2
Authorization: Bearer


### 게시물 신청 폼 조회
GET http://52.79.241.162:8080/posts/1/form
Authorization: Bearer


### 댓글 작성
POST http://52.79.241.162:8080/posts/3/comments
Content-Type: application/json
Authorization: Bearer

{
  "content": "ㅋㅋㅋㅋㅋ"
}


### 모집 신청
POST http://52.79.241.162:8080/posts/1/attend
Content-Type: application/json
Authorization: Bearer

{
  "answers": [
    {
      "itemId": 1,
      "answer": "https://github.com/abcd"
    },
    {
      "itemId": 2,
      "answer": "백엔드"
    }
  ]
}


### 모집 신청
POST http://52.79.241.162:8080/posts/1/attend
Content-Type: application/json
Authorization: Bearer

{
  "answers": [
    {
      "itemId": 1,
      "answer": "ㅎㅎㅎㅎㅎ"
    },
    {
      "itemId": 2,
      "answer": "ㅋㅋㅋㅋㅋ"
    }
  ]
}


### 알림 확인(host)
GET http://52.79.241.162:8080/notifications
Authorization: Bearer


### 신청 수락
POST http://52.79.241.162:8080/posts/1/participations/2/accept
Authorization: Bearer


### 신청 거절
POST http://52.79.241.162:8080/posts/1/participations/3/reject
Authorization: Bearer


### 알림 확인
GET http://52.79.241.162:8080/notifications
Authorization: Bearer


### 모집 완료(host)
POST http://52.79.241.162:8080/posts/1/complete
Authorization: Bearer
