### 게시물 생성
POST http://localhost:8080/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjg1NTM3MDM5LCJleHAiOjE2ODU1NDA2Mzl9._-cY26C3HJkk-g8YvQ8NiiWNx02wDZfhzRIaMOT2ip8

{
  "operationWay": "온라인",
  "headCount": 3,
  "expectedDate": "2023-06-01",
  "title": "스터디 모집합니다",
  "estimatedDuration": "3개월",
  "content": "꾸준히 하실 분",
  "items": [
    "Github",
    "흥미있는 분야"
  ]
}

### 게시물 조회
GET http://localhost:8080/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjg1NTM3MDM5LCJleHAiOjE2ODU1NDA2Mzl9._-cY26C3HJkk-g8YvQ8NiiWNx02wDZfhzRIaMOT2ip8

### 게시물 신청 폼 조회
GET http://localhost:8080/posts/1/form

### 게시물 신청
POST http://localhost:8080/posts/1/attend
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjg1NTM3NTgzLCJleHAiOjE2ODU1NDExODN9.-RqdAKCYIHcgSoBtjUI26YcZfnzb4sC2PEAiXIw7k7A

{
  "answers": [
    {
      "itemId": 1,
      "answer": "abcd"
    },
    {
      "itemId": 2,
      "answer": "백엔드"
    }
  ]
}
