version: "3.9"
services:
  local-db:
    image: mysql:8.0.32
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MOYEOU_DB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Seoul
